name: Zabbix APK Builder
run-name: ${{ gitea.actor }} is building Zabbix APK packages 🚀

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build even if version unchanged'
        required: false
        default: 'false'
        type: boolean

  # Trigger on pushes to main/test branch
  push:
    branches: [ main, test ]
    paths: [ 'zabbix-apk-builder/**' ]

jobs:
  # Simple test job to verify workflow triggers
  test-trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Test workflow trigger
      run: |
        echo "🎉 Build workflow was triggered!"
        echo "Event: ${{ gitea.event_name }}"
        echo "Branch: ${{ gitea.ref }}"
        echo "Repository: ${{ gitea.repository }}"
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: List files in the repository
      run: |
        ls ${{ gitea.workspace }}
        ls ${{ gitea.workspace }}/zabbix-apk-builder/
